#!/bin/bash

sudo docker exec -it mn.appserver sh -c "cd /workdir/in-cse && ./start.sh" &
sudo docker exec -it mn.gi sh -c "cd /workdir/mn-cse && ./start.sh" &
sudo docker exec -it mn.gf1 sh -c "cd /workdir/mn-cse && ./start.sh" &
sudo docker exec -it mn.gf2 sh -c "cd /workdir/mn-cse && ./start.sh" &
sudo docker exec -it mn.gf3 sh -c "cd /workdir/mn-cse && ./start.sh" &
